### ISSUE TITLE
Missing POM

### ISSUE THREAD

**Issue by giusepperizzo** [ftomassetti/semreview#6]

**Comment by ftomassetti** [comment]
Look inside it.polito.semreview (as the README suggests :D)

Do you want to move it to the root directory?

**Comment by giusepperizzo** [comment]
oh dear, missed it, sorry. 
I would say yes, since I do not see why we should have it in the sub-folder. Am I overlooking something?

**Comment by ftomassetti** [comment]
I am not really a Maven expert, it was just the schema we used to have on SF. If we want to have just one module probably it make sense to move the POM in the root (basically transform it.polito.semreview in the root).
