### ISSUE TITLE
Update e-mails

### ISSUE THREAD

**Issue by ftomassetti** [ftomassetti/semreview#7]
The code refers to our e-mails, I think the best thing would be remove those references and add one list of contacts in the README.

What do you think @giusepperizzo @phisaz ?
I am not including Luca because he is the one who rightfully still has a polito e-mail account

**Comment by giusepperizzo** [comment]
fully agree. I would suggest to use my github account instead. Thanks

**Comment by ftomassetti** [comment]
Ok, then if no one is going to propose a different approach I will remove the contacts from each file and insert instead a paragraph in the README (for Giuseppe I will put a link to his GitHub account).
Later everyone should be able to edit the README from the web interface, changing his own account if he likes to do so.
